import { collaboration, education, events, joinRoles, keyStatements, navItems, news, people, platforms, researchAreas, site, stats } from './data/site.js';

const $ = (selector) => document.querySelector(selector);
const card = (inner, cls = '') => `<article class="card ${cls}">${inner}</article>`;
const chips = (items) => `<div class="chips">${items.map((item) => `<span class="chip">${item}</span>`).join('')}</div>`;
const head = (eyebrow, title, desc = '', center = false) => `<div class="section-head ${center ? 'center' : ''}"><p class="eyebrow">${eyebrow}</p><h2>${title}</h2>${desc ? `<p>${desc}</p>` : ''}</div>`;

function header() {
  return `<header class="header"><div class="shell nav"><a class="brand" href="/"><div class="logo">NJU</div><div><b>${site.name}</b><span>${site.shortName}</span></div></a><nav class="links">${navItems.map((n) => `<a href="${n.href}">${n.label}</a>`).join('')}</nav><div><button class="lang" id="langBtn">中文 / EN</button><button class="menu" id="menuBtn">菜单</button></div></div><nav class="mobile shell" id="mobileNav">${navItems.map((n) => `<a href="${n.href}"><b>${n.zh}</b> <span>${n.label}</span></a>`).join('')}</nav></header>`;
}
function footer() {
  return `<footer class="footer"><div class="shell foot-grid"><div><h2>${site.name}</h2><p>${site.englishName}</p><p>面向未来制造体系，建设材料—结构—算法—系统贯通的新工科学院官方网站原型。</p></div><div><h3>快速链接</h3>${navItems.slice(0,8).map((n)=>`<p><a href="${n.href}">${n.zh}</a></p>`).join('')}</div><div><h3>联系方式</h3><p>地址：${site.address}</p><p>邮编：${site.postalCode}</p><p>电话：${site.phone}</p><p>邮箱：${site.email}</p><p>${['WeChat','LinkedIn','X'].map((s)=>`<span class="chip">${s}</span>`).join(' ')}</p></div></div><div class="copy">© 2026 ${site.shortName}. Prototype for content and design review.</div></footer>`;
}
function researchGrid() { return `<div class="grid four">${researchAreas.map((r,i)=>card(`<div class="num">0${i+1}</div><h3>${r.title}</h3><p class="eyebrow">${r.en}</p><p>${r.summary}</p>${chips(r.keywords)}<p><a class="btn purple" href="/research#${r.id}">详情入口</a></p>`, 'research')).join('')}</div>`; }
function platformGrid() { return `<div class="grid three">${platforms.map((p)=>card(`<h3>${p.title}</h3><p>${p.summary}</p><h4>关键技术</h4>${chips(p.technologies)}<h4>应用场景</h4><p>${p.scenarios.join(' / ')}</p><a class="btn purple" href="/collaboration">合作入口</a>`)).join('')}</div>`; }
function newsGrid(limit) { return `<div class="grid three">${news.slice(0, limit || news.length).map((n)=>card(`<p><b>${n.date}</b> <span class="chip">${n.category}</span></p><h3>${n.title}</h3><p>${n.excerpt}</p><a class="btn" href="/news">Read More →</a>`)).join('')}</div>`; }

function home() { return `<main><section class="hero"><div class="blob one"></div><div class="blob two"></div><div class="shell hero-grid"><div><p class="eyebrow">Nanjing University · Suzhou Campus</p><h1>${site.name}</h1><p class="en">${site.englishName}</p><p class="tagline">${site.tagline}</p><p class="subtitle">${site.subtitle}</p><div class="actions"><a class="btn primary" href="/about">了解学院</a><a class="btn ghost" href="/research">探索研究方向</a><a class="btn purple" href="/join">加入我们</a></div></div><div class="visual orbit"><div class="visual-card"><b>Materials · Structures · Algorithms · Systems</b><h2>面向跨尺度、多物理场、多学科深度交叉的先进制造创新网络</h2></div><div class="stats">${stats.map((s)=>`<div class="stat"><strong>${s.value}</strong><p>${s.label}</p></div>`).join('')}</div></div></div></section><section class="section"><div class="shell overview">${head('Overview','学院概览',keyStatements[0])}<div class="grid two">${keyStatements.slice(1).map((s,i)=>`<div class="statement ${i===0?'featured':''}"><b>0${i+1}</b><p>${s}</p></div>`).join('')}</div></div></section><section class="section soft"><div class="shell">${head('Research','四大研究方向','围绕未来制造体系中的关键科学问题与工程瓶颈，构建开放、交叉、面向产业需求的研究版图。')}<br>${researchGrid()}</div></section><section class="section"><div class="shell">${head('Platforms','三大科研平台','以平台能力支撑原创研究、关键技术攻关、交叉人才培养和产研协同创新。')}<br>${platformGrid()}</div></section><section class="section deep"><div class="shell grid two"><div>${head('Education','人才培养',`培养理念：${education.philosophy}`)}<a class="btn primary" href="/education">查看培养体系</a></div><div class="grid two">${education.modules.map((m)=>`<div class="module">${m}</div>`).join('')}</div></div></section><section class="section"><div class="shell">${head('News','新闻动态','关注学院建设、平台进展、学术活动与产研合作动态。')}<br>${newsGrid(3)}</div></section><section class="section soft"><div class="shell grid two">${card(`<h3>学术活动</h3>${events.slice(0,3).map((e)=>`<p><b>${e.date} · ${e.type}</b><br>${e.title}</p>`).join('')}<a class="btn purple" href="/events">全部活动</a>`)}${card(`<h3>招聘与招生</h3><p>学院欢迎全球优秀青年人才，研究方向与四大方向相关或具有交叉融合特色者均欢迎申请。</p>${chips(joinRoles)}<a class="btn purple" href="/join">投递简历 / 联系我们</a>`)}</div></section></main>`; }
function about() { const blocks=[['学院简介',keyStatements[0]],['办学定位',keyStatements[1]],['发展愿景','建设具有南京大学学科底蕴、苏州校区应用与集成特色、面向国际前沿的先进制造创新学院。'],['苏州校区区位优势','依托长三角产业集群与苏州创新生态，推动基础研究、工程技术、平台能力与产业场景高效连接。']]; return `<main><section class="section deep"><div class="shell">${head('About','学院概况',site.mission)}</div></section><section class="section"><div class="shell">${head('Profile','南京大学新工科建设的先锋力量','学院围绕国家战略、学科交叉与区域产业创新需求，打造先进制造技术创新高地。')}<br><div class="grid two">${blocks.map(([t,d])=>card(`<h3>${t}</h3><p>${d}</p>`)).join('')}</div><div class="statement"><p class="eyebrow">Mission</p><h2>${site.mission}</h2></div></div></section></main>`; }
function research() { return `<main><section class="section"><div class="shell">${head('Research','研究方向',keyStatements[2])}<br>${researchGrid()}</div></section><section class="section soft"><div class="shell grid">${researchAreas.map((r,i)=>card(`<p class="eyebrow">Direction 0${i+1}</p><h3 id="${r.id}">${r.title}</h3><p>${r.en}</p><p>${r.summary}</p>${chips(r.keywords)}`)).join('')}</div></section></main>`; }
function platformsPage(){return `<main><section class="section"><div class="shell">${head('Platforms','科研平台','三大科研平台面向基础研究、关键技术突破、工程验证和开放合作提供支撑。')}<br>${platformGrid()}</div></section></main>`;}
function educationPage(){return `<main><section class="section"><div class="shell">${head('Education','人才培养',`培养理念：${education.philosophy}`)}<div class="grid three programs">${education.programs.map((p)=>card(`<p class="eyebrow">${p.title}</p><h3>${p.name}</h3><span class="chip">${p.status}</span>`)).join('')}</div><div class="statement modules"><h3>课程模块</h3><div class="grid four">${education.modules.map((m)=>`<div class="module">${m}</div>`).join('')}</div></div></div></section></main>`;}
function peoplePage(){return `<main><section class="section soft"><div class="shell">${head('People','师资队伍','静态样例页面使用占位数据，后续可替换为真实教师信息、照片、主页链接与研究成果。')}<div class="chips" id="peopleFilters">${['全部',...new Set(people.map(p=>p.area))].map((a,i)=>`<button class="filter ${i===0?'active':''}" data-area="${a}">${a}</button>`).join('')}</div><div class="grid three" id="peopleGrid"></div></div></section></main>`;}
function renderPeople(area='全部'){ const grid=$('#peopleGrid'); if(!grid)return; grid.innerHTML=(area==='全部'?people:people.filter(p=>p.area===area)).map((p)=>card(`<div class="avatar">${p.englishName.slice(-1)}</div><h3>${p.name}</h3><p>${p.englishName}</p><p><b>${p.title}</b></p><p>研究方向：${p.area}</p><p>邮箱：${p.email}</p><button class="btn">个人主页</button>`)).join(''); }
function newsPage(){return `<main><section class="section soft"><div class="shell">${head('News','新闻动态','新闻卡片包含日期、分类、标题、摘要和 Read More 入口，后续可接入真实 CMS。')}<br>${newsGrid()}</div></section></main>`;}
function eventsPage(){return `<main><section class="section"><div class="shell">${head('Events','学术活动','覆盖学术报告、招生宣讲、企业交流与国际工作坊。')}<div class="grid programs">${events.map((e)=>card(`<div class="event-row"><div><b>${e.date}</b><p>${e.time}</p></div><div><span class="chip">${e.type}</span><h3>${e.title}</h3><p>${e.location} · ${e.speaker}</p></div><button class="btn purple">报名</button></div>`)).join('')}</div></div></section></main>`;}
function joinPage(){return `<main><section class="section"><div class="shell grid two"><div>${head('Join Us','加入我们','学院欢迎全球优秀青年人才，研究方向与四大方向相关或具有交叉融合特色者均欢迎申请。')}${chips(joinRoles)}<div class="statement featured"><h3>联系邮箱</h3><p>${site.hrEmail}</p><p>请准备个人简历、研究计划、代表性成果和未来工作设想。招生政策、岗位条件与待遇以后续正式公告为准。</p></div></div><form class="form" id="joinForm"><div class="fields"><label>姓名<input required name="name"></label><label>邮箱<input required type="email" name="email"></label><label>申请岗位<select>${joinRoles.map(r=>`<option>${r}</option>`).join('')}</select></label><label>研究方向<select>${researchAreas.map(r=>`<option>${r.title}</option>`).join('')}</select></label></div><label>留言<textarea rows="6"></textarea></label><button class="btn purple">投递简历 / 联系我们</button><div id="formMsg"></div></form></div></section></main>`;}
function collaborationPage(){return `<main><section class="section"><div class="shell">${head('Collaboration','产研合作',keyStatements[3])}<div class="grid four programs">${collaboration.process.map((p,i)=>card(`<p class="eyebrow">Step 0${i+1}</p><h3>${p}</h3>`)).join('')}</div><div class="statement featured"><h2>面向产业</h2>${chips(collaboration.industries)}</div></div></section></main>`;}
function contactPage(){return `<main><section class="section soft"><div class="shell grid two"><div>${head('Contact','联系我们','欢迎教师、学生、申请人、企业合作伙伴和国际访问者与学院联系。')}<p>地址：${site.address}</p><p>邮编：${site.postalCode}</p><p>电话：${site.phone}</p><p>邮箱：${site.email}</p></div><div class="map"><div class="pin"></div><h2>苏州校区位置占位图</h2><p>此处为地图区域占位，不嵌入真实地图 API。后续可替换为校区地图、交通导引或合规地图服务。</p></div></div></section></main>`;}
function page(){const p=location.pathname; if(p.startsWith('/about'))return about(); if(p.startsWith('/research'))return research(); if(p.startsWith('/platforms'))return platformsPage(); if(p.startsWith('/people'))return peoplePage(); if(p.startsWith('/education'))return educationPage(); if(p.startsWith('/news'))return newsPage(); if(p.startsWith('/events'))return eventsPage(); if(p.startsWith('/join'))return joinPage(); if(p.startsWith('/collaboration'))return collaborationPage(); if(p.startsWith('/contact'))return contactPage(); return home();}

$('#app').innerHTML = header() + page() + footer();
$('#menuBtn')?.addEventListener('click',()=>$('#mobileNav')?.classList.toggle('open'));
$('#langBtn')?.addEventListener('click',(e)=>{e.currentTarget.textContent=e.currentTarget.textContent.startsWith('中文')?'EN / 中文':'中文 / EN';});
renderPeople();
$('#peopleFilters')?.addEventListener('click',(e)=>{const btn=e.target.closest('button'); if(!btn)return; document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); renderPeople(btn.dataset.area);});
$('#joinForm')?.addEventListener('submit',(e)=>{e.preventDefault(); e.currentTarget.reset(); $('#formMsg').innerHTML='<p class="success">提交成功，此功能为原型展示。</p>';});
